# Generated by Django 5.2 on 2025-04-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hiring', '0002_service_securitycompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('applicant', 'Applicant'), ('employer', 'Employer')], max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
