# Generated by Django 5.2 on 2025-04-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hiring', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('employer', 'Employer'), ('client', 'Client')], max_length=50),
        ),
    ]
