# Generated by Django 5.2 on 2025-04-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hiring', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitycompany',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
        migrations.AlterField(
            model_name='securitycompany',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
