# Generated by Django 5.2 on 2025-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hiring', '0006_securitycompany_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitycompany',
            name='services_offered',
        ),
        migrations.AddField(
            model_name='securitycompany',
            name='services_offered',
            field=models.TextField(blank=True),
        ),
    ]
