# Generated by Django 5.2 on 2025-05-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hiring', '0011_delete_service_remove_applicant_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='job',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
