# Generated by Django 5.2.1 on 2025-05-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hiring', '0015_job_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
