# Generated by Django 5.2.1 on 2025-05-26 03:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hiring', '0016_job_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_hiring.client')),
                ('security_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_hiring.securitycompany')),
            ],
        ),
    ]
