# Generated by Django 5.2.1 on 2025-05-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hiring', '0017_hire'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
