# Generated by Django 5.2.1 on 2025-05-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hiring', '0018_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('hired', 'Hired'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
